version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: gitcrm-mongo
    # Порт НЕ публікуємо (бек ходить по внутрішній мережі: mongodb://mongo:27017)
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gitcrm-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      # усередині контейнера бек звертається до mongo по імені сервісу
      MONGO_URI: mongodb://mongo:27017/gitcrm
      PORT: 4000
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gitcrm-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      REACT_APP_API_URL: http://localhost:4000
      HOST: 0.0.0.0
      WDS_SOCKET_PORT: 0
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    restart: unless-stopped

  mongo_express:
    image: mongo-express:1.0.2
    container_name: gitcrm-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_started
    restart: unless-stopped

volumes:
  mongo_data:
